export const SET_USERNAME = 'SET_USERNAME'

export const SET_LANG = 'SET_LANG'

export const SET_DATEFORMAT = 'SET_DATEFORMAT'

export const EDIT_EVENTS = 'EDIT_EVENTS'
export const TOGGLE_EVENT = 'TOGGLE_EVENT'

export const ADD_DEFAULT_ACTIVITY = 'ADD_DEFAULT_ACTIVITY'
export const REMOVE_DEFAULT_ACTIVITY = 'REMOVE_DEFAULT_ACTIVITY'
export const EDIT_DEFAULT_ACTIVITY = 'EDIT_DEFAULT_ACTIVITY'
export const SET_DEFAULT_ACTIVITIES = 'SET_DEFAULT_ACTIVITIES'
