export const ADD_PROJECT = 'ADD_PROJECT'
export const REMOVE_PROJECT = 'REMOVE_PROJECT'
export const EDIT_PROJECT = 'EDIT_PROJECT'

export const ADD_PROJECT_ACTIVITY = 'ADD_PROJECT_ACTIVITY'
export const REMOVE_PROJECT_ACTIVITY = 'REMOVE_PROJECT_ACTIVITY'
export const EDIT_PROJECT_ACTIVITY = 'EDIT_PROJECT_ACTIVITY'
