export const START_RECORD = 'START_RECORD'
export const END_RECORD = 'END_RECORD'

export const START_SEGMENT = 'START_SEGMENT'
export const EDIT_SEGMENT = 'EDIT_SEGMENT'
export const END_SEGMENT = 'END_SEGMENT'
export const CANCEL_SEGMENT = 'CANCEL_SEGMENT'

export const SET_EVENT_OCCURED = 'SET_EVENT_OCCURED'
